on:
  push:
    branches:
      - main
    paths:
      - frontend/**

env:
  PROJECT_ID: subdao-verification
  GAR_LOCATION: asia-southeast1
  REPOSITORY: subdao
  SERVICE: subdao-frontend
  REGION: asia-southeast1

defaults:
  run:
    working-directory: ./frontend

jobs:
  # JOB to build and test frontend code
  frontend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Production Code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.CREDENTIALS }}

      - name: Docker auth
        id: docker-auth
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.CREDENTIALS }}

      - name: Docker build frontend
        run: docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./

      - name: Docker push frontend
        run: docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Allow public access
        id: unauthenticated
        run: gcloud run services add-iam-policy-binding ${{ env.SERVICE }} --region=${{ env.REGION }} --member="allUsers" --role="roles/run.invoker"

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
